### ISSUE TITLE
Fresh install: error 400

### ISSUE THREAD

**Issue by retiolus** [YunoHost-Apps/languagetool_ynh#22]
### Context

- Hardware: rpi4
- YunoHost version: 11.0.10 (stable)
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 5.8~ynh1

### Steps to reproduce

- Install languagetool server on a subdomain, ex: languagetool.home.server.example
- set up custom url (languagetool.home.server.example) on browser extension (both chrome and firefox)
- test writing in any page, doesn't work: error 400

### Logs

```
LOGFILE: journalctl
-- Journal begins at Mon 2022-08-08 11:55:54 BST, ends at Thu 2022-10-27 18:33:45 BST. --
Oct 27 01:19:16 systemd[1]: Started Spelling and grammar checking server.

LOGFILE: /var/log/languagetool/languagetool.log
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:730)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:699)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-10-27 18:32:05.843 +0100 INFO  org.languagetool.server.LanguageToolHttpHandler An error has occurred: 'This is the LanguageTool API. You have not specified any parameters. Please see https://languagetool.org/http-api/swagger-ui/#/default', sending HTTP code 400. Access from 127.0.0.1, HTTP user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36, User agent param: webextension-chrome-ng, v: 5.4.3, Referrer: null, language: auto, h: 2, r: 256, time: 1m: TEXTLEVEL_ONLY, l: PICKY, iID: 2974:1666891913637, Stacktrace follows:org.languagetool.server.BadRequestException: This is the LanguageTool API. You have not specified any parameters. Please see https://languagetool.org/http-api/swagger-ui/#/default
	at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:195)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:730)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:699)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-10-27 18:32:05.844 +0100 INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 2ms; sending code 400
2022-10-27 18:32:05.844 +0100 INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 2ms; sending code 400
2022-10-27 18:32:07.881 +0100 INFO  org.languagetool.server.LanguageToolHttpHandler Handling POST /check
2022-10-27 18:32:07.881 +0100 INFO  org.languagetool.server.LanguageToolHttpHandler Handling POST /check
2022-10-27 18:32:07.883 +0100 INFO  org.languagetool.server.LanguageToolHttpHandler An error has occurred: 'This is the LanguageTool API. You have not specified any parameters. Please see https://languagetool.org/http-api/swagger-ui/#/default', sending HTTP code 400. Access from 127.0.0.1, HTTP user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36, User agent param: webextension-chrome-ng, v: 5.4.3, Referrer: null, language: auto, h: 2, r: 258, time: 2m: TEXTLEVEL_ONLY, l: PICKY, iID: 2974:1666891913637, Stacktrace follows:org.languagetool.server.BadRequestException: This is the LanguageTool API. You have not specified any parameters. Please see https://languagetool.org/http-api/swagger-ui/#/default
	at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:195)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:730)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:699)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-10-27 18:32:07.883 +0100 INFO  org.languagetool.server.LanguageToolHttpHandler An error has occurred: 'This is the LanguageTool API. You have not specified any parameters. Please see https://languagetool.org/http-api/swagger-ui/#/default', sending HTTP code 400. Access from 127.0.0.1, HTTP user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36, User agent param: webextension-chrome-ng, v: 5.4.3, Referrer: null, language: auto, h: 2, r: 258, time: 2m: ALL_BUT_TEXTLEVEL_ONLY, l: PICKY, iID: 2974:1666891913637, Stacktrace follows:org.languagetool.server.BadRequestException: This is the LanguageTool API. You have not specified any parameters. Please see https://languagetool.org/http-api/swagger-ui/#/default
	at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:195)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:730)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:699)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-10-27 18:32:07.885 +0100 INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 4ms; sending code 400
2022-10-27 18:32:07.885 +0100 INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 4ms; sending code 400
```

**Comment by Jules-Bertholet** [comment]
In the browser extension settings, you need to append `/v2` to the URL

**Comment by retiolus** [comment]
Now it works some times and sometimes I get a 502 error. In any case, maybe adding `/v2` to the end of the URL should be specified in the README! :)

**Comment by theRAGEhero** [comment]
Hello,I think I have the same problem.

I've installed LT on a rpi3 (on a subdomain) and what happen is if I browse on that domain I see a 502 error. Only one time it happened to me to see the different languages in json style.

https://paste.yunohost.org/wutomunogo

I tried with different extension but it doesn't work at all. The process crashes.

Thank you.
